// home_product.js

const Homeproduct = [
    {
      id: 1,
      Name: "Product1",
      price: '100',
      image: `${process.env.PUBLIC_URL}/image/p1.webp`,
      cat: 'tv',
      type: 'new',
    },
    {
      id: 2,
      Name: "Product2",
      price: '120',
      image: `${process.env.PUBLIC_URL}/image/p2.webp`,
      cat: 'laptop',
      type: 'new',
    },
    {
      id: 3,
      Name: "Product3",
      price: '140',
      image: `${process.env.PUBLIC_URL}/image/p3.webp`,
      cat: 'watch',
      type: 'new',
    },
    {
      id: 4,
      Name: "Product4",
      price: '450',
      image: `${process.env.PUBLIC_URL}/image/p9.jpg`,
      cat:'laptop',
      type: 'new',
    },
    {
      id: 5,
      Name: "Product5",
      price: '160',
      image: `${process.env.PUBLIC_URL}/image/p4.webp`,
      cat: 'speaker',
      type: 'featured',
    },
    {
      id: 6,
      Name: "Product6",
      price: '180',
      image: `${process.env.PUBLIC_URL}/image/p5.webp`,
      cat: 'electronics',
      type: 'featured',
    },
    {
      id: 7,
      Name: "Product7",
      price: '879',
      image: `${process.env.PUBLIC_URL}/image/p10.jpg`,
      cat: 'headphone',
      type: 'featured',
    },
    {
      id: 8,
      Name: "Product8",
      price: '979',
      image: `${process.env.PUBLIC_URL}/image/p11.jpg`,
      cat: 'electronics',
      type: 'featured',
    },
    {
      id: 9,
      Name: "Product9",
      price: '600',
      image: `${process.env.PUBLIC_URL}/image/p6.webp`,
      cat: 'phone',
      type: 'top',
    },
    {
      id: 10,
      Name: "Product10",
      price: '220',
      image: `${process.env.PUBLIC_URL}/image/p7.webp`,
      cat: 'speaker',
      type: 'top',
    },
    {
      id: 11,
      Name: "Product11",
      price: '240',
      image: `${process.env.PUBLIC_URL}/image/p8.webp`,
      cat: 'speaker',
      type: 'top',
    },
    {
      id: 12,
      Name: "Product12",
      price: '540',
      image: `${process.env.PUBLIC_URL}/image/p12.jpg`,
      cat: 'speaker',
      type: 'top',
    },
  ];
  
  export default Homeproduct;
  